package LanguageHTML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnchorElement = createDescriptorForAnchorElement();
  /*package*/ final ConceptDescriptor myConceptBody = createDescriptorForBody();
  /*package*/ final ConceptDescriptor myConceptBodyElement = createDescriptorForBodyElement();
  /*package*/ final ConceptDescriptor myConceptDivElement = createDescriptorForDivElement();
  /*package*/ final ConceptDescriptor myConceptDocument = createDescriptorForDocument();
  /*package*/ final ConceptDescriptor myConceptHead = createDescriptorForHead();
  /*package*/ final ConceptDescriptor myConceptHeadChild = createDescriptorForHeadChild();
  /*package*/ final ConceptDescriptor myConceptHtmlDocument = createDescriptorForHtmlDocument();
  /*package*/ final ConceptDescriptor myConceptHtmlElement = createDescriptorForHtmlElement();
  /*package*/ final ConceptDescriptor myConceptItalicTag = createDescriptorForItalicTag();
  /*package*/ final ConceptDescriptor myConceptParagraphElement = createDescriptorForParagraphElement();
  /*package*/ final ConceptDescriptor myConceptSpanElement = createDescriptorForSpanElement();
  /*package*/ final ConceptDescriptor myConceptStrongElement = createDescriptorForStrongElement();
  /*package*/ final ConceptDescriptor myConceptTextElement = createDescriptorForTextElement();
  /*package*/ final ConceptDescriptor myConceptTitleElement = createDescriptorForTitleElement();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnchorElement, myConceptBody, myConceptBodyElement, myConceptDivElement, myConceptDocument, myConceptHead, myConceptHeadChild, myConceptHtmlDocument, myConceptHtmlElement, myConceptItalicTag, myConceptParagraphElement, myConceptSpanElement, myConceptStrongElement, myConceptTextElement, myConceptTitleElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AnchorElement:
        return myConceptAnchorElement;
      case LanguageConceptSwitch.Body:
        return myConceptBody;
      case LanguageConceptSwitch.BodyElement:
        return myConceptBodyElement;
      case LanguageConceptSwitch.DivElement:
        return myConceptDivElement;
      case LanguageConceptSwitch.Document:
        return myConceptDocument;
      case LanguageConceptSwitch.Head:
        return myConceptHead;
      case LanguageConceptSwitch.HeadChild:
        return myConceptHeadChild;
      case LanguageConceptSwitch.HtmlDocument:
        return myConceptHtmlDocument;
      case LanguageConceptSwitch.HtmlElement:
        return myConceptHtmlElement;
      case LanguageConceptSwitch.ItalicTag:
        return myConceptItalicTag;
      case LanguageConceptSwitch.ParagraphElement:
        return myConceptParagraphElement;
      case LanguageConceptSwitch.SpanElement:
        return myConceptSpanElement;
      case LanguageConceptSwitch.StrongElement:
        return myConceptStrongElement;
      case LanguageConceptSwitch.TextElement:
        return myConceptTextElement;
      case LanguageConceptSwitch.TitleElement:
        return myConceptTitleElement;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnchorElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "AnchorElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a872acaL);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387663050");
    b.version(3);
    b.property("href", 0x2263eb887a872c52L).type(PrimitiveTypeId.STRING).origin("2478083191387663442").done();
    b.aggregate("children", 0x7a7699b586c6a4abL).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(false).ordered(true).multiple(true).origin("8824409524808361131").done();
    b.alias("<anchor>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "Body", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x7a7699b586cbaa23L);
    b.class_(false, false, false);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/8824409524808690211");
    b.version(3);
    b.aggregate("children", 0x7a7699b586cbb056L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(true).ordered(true).multiple(true).origin("8824409524808691798").done();
    b.alias("<body>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBodyElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "BodyElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.class_(false, true, false);
    // extends: LanguageHTML.structure.HtmlElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a86e354L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387619893");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDivElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "DivElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a871eeeL);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387660014");
    b.version(3);
    b.property("class", 0x29b0bc23fbba0a76L).type(PrimitiveTypeId.STRING).origin("3004107814189271670").done();
    b.aggregate("children", 0x2263eb887a87212eL).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(false).ordered(true).multiple(true).origin("2478083191387660590").done();
    b.alias("<div>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "Document", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a86cc2fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387638831");
    b.version(3);
    b.aggregate("root", 0x2263eb887a86d93dL).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a867ce3L).optional(false).ordered(true).multiple(false).origin("2478083191387642173").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHead() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "Head", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x7a7699b586cba882L);
    b.class_(false, false, false);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/8824409524808689794");
    b.version(3);
    b.aggregate("children", 0x7a7699b586cbb622L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a86e354L).optional(true).ordered(true).multiple(true).origin("8824409524808693282").done();
    b.alias("<head>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHeadChild() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "HeadChild", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a8704b9L);
    b.class_(false, true, false);
    // extends: LanguageHTML.structure.HtmlElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a86e354L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387653305");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtmlDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "HtmlDocument", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a867ce3L);
    b.class_(false, false, false);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387618531");
    b.version(3);
    b.aggregate("head", 0x2263eb887a86e24dL).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x7a7699b586cba882L).optional(true).ordered(true).multiple(false).origin("2478083191387644493").done();
    b.aggregate("body", 0x2263eb887a86ea77L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x7a7699b586cbaa23L).optional(true).ordered(true).multiple(false).origin("2478083191387646583").done();
    b.alias("<html>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtmlElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "HtmlElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a86e354L);
    b.class_(false, true, false);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387644756");
    b.version(3);
    b.property("tagName", 0x2263eb887a86e62fL).type(PrimitiveTypeId.STRING).origin("2478083191387645487").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForItalicTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "ItalicTag", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x194f0d7ef32b4674L);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/1823691213005080180");
    b.version(3);
    b.aggregate("children", 0x194f0d7ef32b4cf6L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(true).ordered(true).multiple(true).origin("1823691213005081846").done();
    b.alias("<i>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParagraphElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "ParagraphElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a872889L);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387662473");
    b.version(3);
    b.aggregate("children", 0x194f0d7ef32a04e9L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(true).ordered(true).multiple(true).origin("1823691213004997865").done();
    b.alias("<paragraph>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpanElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "SpanElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a87248dL);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387661453");
    b.version(3);
    b.property("class", 0x29b0bc23fbb7c847L).type(PrimitiveTypeId.STRING).origin("3004107814189123655").done();
    b.aggregate("children", 0x7a7699b586c4eb86L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(false).ordered(true).multiple(true).origin("8824409524808248198").done();
    b.alias("<span>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStrongElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "StrongElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x194f0d7ef328cb64L);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/1823691213004917604");
    b.version(3);
    b.aggregate("children", 0x194f0d7ef328dce2L).target(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L).optional(false).ordered(true).multiple(true).origin("1823691213004922082").done();
    b.alias("<strong>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "TextElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a86a58bL);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.BodyElement
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a868235L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387628939");
    b.version(3);
    b.property("text", 0x2263eb887a86a84cL).type(PrimitiveTypeId.STRING).origin("2478083191387629644").done();
    b.alias("<text>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTitleElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LanguageHTML", "TitleElement", 0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a870e67L);
    b.class_(false, false, false);
    // extends: LanguageHTML.structure.HeadChild
    b.super_(0xcfdb8e6e45b145d3L, 0xa650bdfedc3caeb8L, 0x2263eb887a8704b9L);
    b.origin("r:25f659e2-b953-412a-a6d6-807442bcb348(LanguageHTML.structure)/2478083191387655783");
    b.version(3);
    b.property("text", 0x2263eb887a87122cL).type(PrimitiveTypeId.STRING).origin("2478083191387656748").done();
    b.alias("<title>");
    return b.create();
  }
}
